"""
Thai WHT Calculation Override for Purchase Order
Prevents ERPNext standard Tax Withholding Category interference
and provides precise Thai-compliant WHT calculations
"""

import frappe
from frappe.utils import flt, cint
from frappe import _

@frappe.whitelist()
def override_purchase_order_wht_calculation(doc, method=None):
    """
    Override ERPNext's standard WHT calculation for Thai compliance.
    Called via hooks to intercept and replace standard ERPNext WHT logic.

    Args:
        doc: Purchase Order document
        method: Hook method name
    """

    # Only process if Thai WHT system is enabled
    if not getattr(doc, 'apply_thai_wht_compliance', 0) or not getattr(doc, 'subject_to_wht', 0):
        return

    # Prevent ERPNext's standard Tax Withholding Category calculation
    disable_standard_wht_calculation(doc)

    # Apply Thai-specific WHT calculation
    calculate_thai_compliant_wht(doc)

    frappe.logger().info(f"Thai WHT Override applied to Purchase Order {doc.name}")


def disable_standard_wht_calculation(doc):
    """
    Prevent ERPNext's automatic Tax Withholding Category calculation
    by removing any auto-generated tax withholding entries
    """

    if not hasattr(doc, 'taxes') or not doc.taxes:
        return

    # Remove any tax entries that were auto-generated by ERPNext's WHT system
    taxes_to_remove = []
    for idx, tax in enumerate(doc.taxes):
        if tax.account_head and 'withholding' in tax.account_head.lower():
            taxes_to_remove.append(idx)

    # Remove in reverse order to maintain indices
    for idx in reversed(taxes_to_remove):
        doc.taxes.pop(idx)

    frappe.logger().info(f"Removed {len(taxes_to_remove)} ERPNext WHT tax entries")


def calculate_thai_compliant_wht(doc):
    """
    Calculate WHT using Thai compliance rules:
    - Use net_total (before VAT) as calculation base
    - Apply precise percentage calculation without rounding quirks
    - Support Thai retention system integration
    """

    # DEBUGGING: Show document totals FIRST (before any early returns)
    print(f"\n{'='*80}")
    print(f"🔍 DOCUMENT TOTALS DEBUG (BEFORE get_wht_calculation_base)")
    print(f"{'='*80}")

    # Get WHT rate from custom field
    wht_rate = flt(getattr(doc, 'custom_withholding_tax', 0))
    print(f"📋 WHT Rate: {wht_rate}%")

    if wht_rate <= 0:
        print(f"⚠️ WHT rate is 0 or negative, exiting early")
        print(f"{'='*80}\n")
        return
    print(f"📊 Document Level Totals:")
    print(f"   - base_total (Company Currency):     {flt(getattr(doc, 'base_total', 0))}")
    print(f"   - total (Transaction Currency):      {flt(getattr(doc, 'total', 0))}")
    print(f"   - base_net_total (before discount):  {flt(getattr(doc, 'base_net_total', 0))}")
    print(f"   - net_total (before discount):       {flt(getattr(doc, 'net_total', 0))}")
    print(f"📦 Items:")
    print(f"   - Number of items: {len(doc.items) if hasattr(doc, 'items') and doc.items else 0}")
    if hasattr(doc, 'items') and doc.items:
        for idx, item in enumerate(doc.items):
            print(f"   - Item {idx+1}: {getattr(item, 'item_code', 'Unknown')} | Amount: {flt(getattr(item, 'amount', 0))}")
    print(f"{'='*80}\n")

    # Calculate WHT base amount (SERVICE ITEMS ONLY - Thai tax law)
    wht_base_amount = get_wht_calculation_base(doc)

    # Calculate RETENTION base amount (WHOLE INVOICE - contract guarantee)
    # Priority: base_total (Company Currency) → total (Transaction Currency)
    retention_base_amount = flt(getattr(doc, 'base_total', 0)) or flt(getattr(doc, 'total', 0))

    # DEBUGGING: Show result AFTER calculation
    print(f"\n{'='*80}")
    print(f"📊 WHT Base (service items only): {wht_base_amount}")
    print(f"📊 Retention Base (whole invoice): {retention_base_amount}")
    print(f"   - base_total: {flt(getattr(doc, 'base_total', 0))}")
    print(f"   - total: {flt(getattr(doc, 'total', 0))}")
    print(f"{'='*80}\n")

    # Precise WHT calculation: wht_base × rate ÷ 100 (SERVICE ITEMS ONLY)
    wht_amount = flt(wht_base_amount * wht_rate / 100, 2)  # Round to 2 decimal places

    # Update custom WHT fields
    doc.custom_withholding_tax_amount = wht_amount

    # Calculate retention amount if retention is enabled
    print("\n" + "="*80)
    print("🔍 RETENTION CALCULATION DEBUG START")
    print("="*80)

    custom_subject_to_retention = getattr(doc, 'custom_subject_to_retention', 0)
    has_custom_retention = hasattr(doc, 'custom_retention')
    print(f"1. custom_subject_to_retention: {custom_subject_to_retention}")
    print(f"2. has custom_retention attr: {has_custom_retention}")

    if custom_subject_to_retention and has_custom_retention:
        retention_percentage = flt(getattr(doc, 'custom_retention', 0))
        print(f"3. retention_percentage: {retention_percentage}%")
        print(f"4. retention_base_amount (WHOLE INVOICE): {retention_base_amount}")

        # Browser debug message
        frappe.msgprint(
            f"🔍 CALC DEBUG: retention_base = {retention_base_amount} (whole invoice), retention % = {retention_percentage}%",
            indicator='orange',
            title="Retention Calculation"
        )

        if retention_percentage > 0:
            # FIXED: Retention is calculated on WHOLE INVOICE, not just services
            # Example: Total 1,000,000 THB (materials 600k + services 400k) × 5% = 50,000 THB retention
            calculated_retention = flt(retention_base_amount * retention_percentage / 100, 2)
            doc.custom_retention_amount = calculated_retention
            print(f"5. ✅ Calculated retention_amount: {retention_base_amount} (whole invoice) × {retention_percentage}% = {calculated_retention}")
            frappe.logger().info(
                f"Retention Calculation: {retention_base_amount} × {retention_percentage}% = {doc.custom_retention_amount}"
            )

            # Browser debug message
            frappe.msgprint(
                f"✅ Calculated retention_amount = {calculated_retention} THB",
                indicator='green',
                title="Retention Calculation Success"
            )
        else:
            print("5. ⚠️ Retention percentage is 0, no calculation")
    else:
        print("3. ❌ Retention not enabled or field missing")

    print("="*80)
    print("🔍 RETENTION CALCULATION DEBUG END")
    print("="*80 + "\n")

    # Calculate final payment amount (after WHT and retention)
    print("\n" + "="*80)
    print("🔍 FINAL PAYMENT CALCULATION DEBUG START")
    print("="*80)

    retention_amount = flt(getattr(doc, 'custom_retention_amount', 0))
    print(f"1. grand_total: {doc.grand_total}")
    print(f"2. wht_amount: {wht_amount}")
    print(f"3. retention_amount: {retention_amount}")

    final_payment = flt(doc.grand_total) - wht_amount - retention_amount
    print(f"4. ✅ final_payment: {doc.grand_total} - {wht_amount} - {retention_amount} = {final_payment}")

    # Browser debug message
    frappe.msgprint(
        f"🔍 FINAL CALC: grand_total = {doc.grand_total}<br>"
        f"WHT = {wht_amount}<br>"
        f"Retention = {retention_amount}<br>"
        f"<b>Final Payment = {final_payment} THB</b>",
        indicator='blue',
        title="Final Payment Calculation"
    )

    doc.custom_payment_amount = final_payment

    print("="*80)
    print("🔍 FINAL PAYMENT CALCULATION DEBUG END")
    print("="*80 + "\n")

    # Update preview fields for user display
    update_thai_wht_preview_fields(doc, wht_base_amount, wht_amount, final_payment)

    frappe.logger().info(
        f"Thai WHT Calculation: {wht_base_amount} × {wht_rate}% = {wht_amount} "
        f"(Final Payment: {final_payment})"
    )


def get_wht_calculation_base(doc):
    """
    Get the correct base amount for WHT calculation.
    Thai WHT should be calculated ONLY on service items, not assets/goods.
    WHT applies to: Item.pd_custom_is_service_item = 1
    """

    # Calculate WHT base from SERVICE ITEMS ONLY
    # WHT does not apply to assets/goods, only to services
    service_items_total = 0.0

    print(f"\n🔍 DEBUG: WHT Base Calculation for {doc.doctype} {doc.name}")
    print(f"📦 DEBUG: Document has {len(doc.items) if hasattr(doc, 'items') else 0} items")

    if hasattr(doc, 'items') and doc.items:
        for idx, item in enumerate(doc.items):
            item_amount = flt(item.amount)
            item_code = getattr(item, 'item_code', 'Unknown')

            print(f"  Item {idx + 1}: {item_code}")
            print(f"    - amount: {item_amount}")

            # Check if item is a service item by querying Item master
            is_service = 0
            if item_code and item_code != 'Unknown':
                try:
                    item_doc = frappe.get_cached_doc('Item', item_code)
                    is_service = getattr(item_doc, 'pd_custom_is_service_item', 0)
                    print(f"    - Item master pd_custom_is_service_item: {is_service}")
                except Exception as e:
                    print(f"    ⚠️ Could not fetch Item master: {e}")
                    is_service = 0

            if is_service:
                # Sum only service item amounts
                service_items_total += item_amount
                print(f"    ✅ INCLUDED in WHT calculation (Service Item)")
            else:
                print(f"    ❌ EXCLUDED from WHT calculation (Asset/Good)")

    print(f"💰 DEBUG: Total Service Items Amount (WHT Base): {service_items_total}")
    print(f"📊 DEBUG: Document net_total for comparison: {getattr(doc, 'net_total', 0)}")

    return flt(service_items_total)


def update_thai_wht_preview_fields(doc, base_amount, wht_amount, final_payment):
    """
    Update Thai WHT preview section fields for better user experience
    """

    # Update net total after WHT field: grand_total - wht_amount
    # This represents: base_amount + VAT - WHT
    doc.net_total_after_wht = flt(doc.grand_total) - wht_amount

    # Update in words fields if they exist
    if hasattr(doc, 'net_total_after_wht_in_words'):
        from frappe.utils import money_in_words
        doc.net_total_after_wht_in_words = money_in_words(
            doc.net_total_after_wht,
            doc.currency
        )

    # Update combined WHT and retention amounts
    if hasattr(doc, 'custom_net_total_after_wht_retention'):
        doc.custom_net_total_after_wht_retention = final_payment

        if hasattr(doc, 'custom_net_total_after_wht_retention_in_words'):
            doc.custom_net_total_after_wht_retention_in_words = money_in_words(
                final_payment,
                doc.currency
            )


@frappe.whitelist()
def validate_thai_wht_configuration(doc, method=None):
    """
    Validate Thai WHT configuration to ensure proper setup
    """

    if not getattr(doc, 'apply_thai_wht_compliance', 0):
        return

    # Validate required fields for Thai WHT
    if getattr(doc, 'subject_to_wht', 0):
        if not getattr(doc, 'wht_income_type'):
            frappe.throw(_("WHT Income Type is required when Subject to Withholding Tax is enabled"))

        # Auto-fetch default WHT rate from Company if not specified
        if not getattr(doc, 'custom_withholding_tax') or flt(getattr(doc, 'custom_withholding_tax', 0)) == 0:
            default_wht_rate = frappe.db.get_value("Company", doc.company, "default_wht_rate")

            if default_wht_rate and flt(default_wht_rate) > 0:
                doc.custom_withholding_tax = flt(default_wht_rate)
                frappe.logger().info(f"Auto-fetched default WHT rate {default_wht_rate}% from Company {doc.company}")

                # Show user-friendly message
                frappe.msgprint(
                    _("Auto-applied default WHT rate {0}% from Company settings").format(flt(default_wht_rate)),
                    indicator='blue'
                )
            else:
                frappe.throw(_("Withholding Tax percentage is required. Please set either in this document or configure a default rate in Company settings."))

    # Auto-fetch default retention rate from Company if applicable
    print("\n" + "="*80)
    print("🔍 RETENTION AUTO-FETCH DEBUG START")
    print("="*80)

    custom_subject_to_retention = getattr(doc, 'custom_subject_to_retention', 0)
    print(f"1. custom_subject_to_retention: {custom_subject_to_retention}")

    # Browser debug message
    frappe.msgprint(
        f"🔍 DEBUG Step 1: custom_subject_to_retention = {custom_subject_to_retention}",
        indicator='orange',
        title="Retention Debug"
    )

    if custom_subject_to_retention:
        print(f"2. Company: {doc.company}")

        # Check if construction_service is enabled for this Company
        construction_service_enabled = frappe.db.get_value("Company", doc.company, "construction_service")
        print(f"3. construction_service_enabled: {construction_service_enabled}")

        # Browser debug message
        frappe.msgprint(
            f"🔍 DEBUG Step 2: Company = {doc.company}<br>construction_service = {construction_service_enabled}",
            indicator='orange',
            title="Retention Debug"
        )

        if construction_service_enabled:
            # Auto-fetch default retention rate if not specified
            current_retention = getattr(doc, 'custom_retention', None)
            current_retention_value = flt(current_retention) if current_retention else 0
            print(f"4. Current custom_retention: {current_retention} (value: {current_retention_value})")

            if not current_retention or current_retention_value == 0:
                print("5. Retention is blank or zero, fetching from Company...")

                default_retention_rate = frappe.db.get_value("Company", doc.company, "default_retention_rate")
                print(f"6. default_retention_rate from Company: {default_retention_rate}")

                # Browser debug message
                frappe.msgprint(
                    f"🔍 DEBUG Step 3: default_retention_rate from Company = {default_retention_rate}%",
                    indicator='orange',
                    title="Retention Debug"
                )

                if default_retention_rate and flt(default_retention_rate) > 0:
                    doc.custom_retention = flt(default_retention_rate)
                    print(f"7. ✅ Set doc.custom_retention to: {doc.custom_retention}")
                    frappe.logger().info(f"Auto-fetched default retention rate {default_retention_rate}% from Company {doc.company}")

                    # Show success message
                    frappe.msgprint(
                        f"✅ Auto-applied default retention rate {flt(default_retention_rate)}% from Company settings",
                        indicator='green',
                        title="Success"
                    )
                else:
                    print("7. ❌ No valid default_retention_rate found in Company")
                    frappe.msgprint(
                        _("Please set retention percentage or configure a default retention rate in Company settings"),
                        indicator='yellow'
                    )
            else:
                print(f"5. Retention already set to {current_retention_value}%, skipping auto-fetch")
        else:
            print("3. ❌ construction_service is NOT enabled on Company")
    else:
        print("1. ❌ custom_subject_to_retention is NOT enabled")

    print("="*80)
    print("🔍 RETENTION AUTO-FETCH DEBUG END")
    print("="*80 + "\n")

    # Validate VAT treatment for TDS transactions
    # Only suggest VAT Undue if document has single item type (not mixed assets + services)
    vat_treatment = getattr(doc, 'vat_treatment', '')
    if vat_treatment and vat_treatment not in ['VAT Undue (7%)', 'Exempt from VAT']:
        # Check if document has mixed item types
        has_mixed_item_types = _check_mixed_item_types(doc)

        # Only show VAT Undue suggestion for single-item-type documents
        if not has_mixed_item_types:
            frappe.msgprint(
                _("Consider using 'VAT Undue (7%)' for TDS transactions to comply with Thai tax regulations"),
                indicator='yellow'
            )


def _check_mixed_item_types(doc):
    """
    Check if document contains mixed item types (both assets and services).
    VAT point occurs immediately for mixed documents, so VAT Undue is not applicable.

    Args:
        doc: Purchase Invoice or Purchase Order document

    Returns:
        bool: True if document has mixed item types (assets + services), False otherwise
    """
    if not hasattr(doc, 'items') or not doc.items:
        return False

    has_assets = False
    has_services = False

    for item in doc.items:
        # Check if item is an asset or service
        if hasattr(item, 'item_code') and item.item_code:
            item_doc = frappe.get_cached_doc('Item', item.item_code)
            is_fixed_asset = getattr(item_doc, 'is_fixed_asset', 0)
            is_stock_item = getattr(item_doc, 'is_stock_item', 0)

            # Asset: is_fixed_asset = 1 OR is_stock_item = 1 (goods)
            # Service: is_fixed_asset = 0 AND is_stock_item = 0
            if is_fixed_asset or is_stock_item:
                has_assets = True
            else:
                has_services = True

        # Early exit if we found both types
        if has_assets and has_services:
            return True

    return False


@frappe.whitelist()
def get_thai_wht_calculation_debug_info(purchase_order_name):
    """
    Debug function to analyze WHT calculation differences
    Returns detailed breakdown of both ERPNext and Thai calculations
    """

    doc = frappe.get_doc("Purchase Order", purchase_order_name)

    debug_info = {
        "document": purchase_order_name,
        "apply_thai_wht_compliance": getattr(doc, 'apply_thai_wht_compliance', 0),
        "subject_to_wht": getattr(doc, 'subject_to_wht', 0),
        "wht_rate": flt(getattr(doc, 'custom_withholding_tax', 0)),
        "amounts": {
            "net_total": flt(getattr(doc, 'net_total', 0)),
            "base_net_total": flt(getattr(doc, 'base_net_total', 0)),
            "total": flt(getattr(doc, 'total', 0)),
            "grand_total": flt(getattr(doc, 'grand_total', 0)),
        },
        "thai_calculation": {},
        "erpnext_calculation": {}
    }

    # Thai calculation
    if debug_info["wht_rate"] > 0:
        base_amount = get_wht_calculation_base(doc)
        thai_wht = flt(base_amount * debug_info["wht_rate"] / 100, 2)

        debug_info["thai_calculation"] = {
            "base_amount": base_amount,
            "calculation": f"{base_amount} × {debug_info['wht_rate']}% = {thai_wht}",
            "wht_amount": thai_wht
        }

    # ERPNext standard calculation (if any tax withholding entries exist)
    if hasattr(doc, 'taxes') and doc.taxes:
        for tax in doc.taxes:
            if tax.account_head and 'withholding' in tax.account_head.lower():
                debug_info["erpnext_calculation"] = {
                    "account": tax.account_head,
                    "tax_amount": flt(tax.tax_amount),
                    "base_tax_amount": flt(tax.base_tax_amount),
                    "rate": flt(tax.rate)
                }
                break

    return debug_info


@frappe.whitelist()
def test_thai_wht_calculation_precision():
    """
    Test function to verify Thai WHT calculation precision
    Tests the critical case: 10,000 × 3% should equal exactly 300 (not 306)
    """

    # Test case that was failing with ERPNext standard calculation
    test_cases = [
        {"base_amount": 10000, "rate": 3, "expected": 300},
        {"base_amount": 5000, "rate": 3, "expected": 150},
        {"base_amount": 15000, "rate": 5, "expected": 750},
        {"base_amount": 100000, "rate": 1, "expected": 1000},
    ]

    results = []

    for case in test_cases:
        # Use same calculation logic as our override
        calculated = flt(case["base_amount"] * case["rate"] / 100, 2)

        test_result = {
            "base_amount": case["base_amount"],
            "rate": case["rate"],
            "expected": case["expected"],
            "calculated": calculated,
            "precise": calculated == case["expected"],
            "calculation_string": f"{case['base_amount']} × {case['rate']}% = {calculated}"
        }

        results.append(test_result)

    # Summary
    all_precise = all(result["precise"] for result in results)

    return {
        "test_results": results,
        "all_calculations_precise": all_precise,
        "message": "✅ All calculations precise!" if all_precise else "❌ Some calculations imprecise",
        "critical_case": f"10,000 × 3% = {flt(10000 * 3 / 100, 2)} (should be 300)"
    }


@frappe.whitelist()
def test_thai_wht_automation():
    """
    Test function to verify the complete Thai WHT automation workflow
    Creates a test Purchase Order to verify field automation and calculation
    """

    try:
        # Create a test Purchase Order with Thai WHT enabled
        test_po = frappe.new_doc("Purchase Order")
        test_po.supplier = "Test Supplier"  # Use a simple supplier name
        test_po.currency = "THB"
        test_po.company = frappe.defaults.get_defaults().get("company")

        # Add a test item
        test_po.append("items", {
            "item_code": "Test Item",
            "description": "Test Service Item",
            "qty": 1,
            "rate": 10000,
            "amount": 10000
        })

        # Calculate totals to simulate ERPNext behavior
        test_po.net_total = 10000
        test_po.total = 10000
        test_po.grand_total = 10000

        # Enable Thai WHT Compliance
        test_po.apply_thai_wht_compliance = 1
        test_po.subject_to_wht = 1
        test_po.custom_withholding_tax = 3  # 3%
        test_po.wht_income_type = "professional_services"

        # Test our calculation override
        calculate_thai_compliant_wht(test_po)

        # Collect results
        results = {
            "test_status": "success",
            "base_amount": flt(test_po.net_total),
            "wht_rate": flt(test_po.custom_withholding_tax),
            "calculated_wht": flt(getattr(test_po, 'custom_withholding_tax_amount', 0)),
            "expected_wht": 300,
            "calculation_correct": flt(getattr(test_po, 'custom_withholding_tax_amount', 0)) == 300,
            "final_payment": flt(getattr(test_po, 'custom_payment_amount', 0)),
            "message": "✅ Thai WHT calculation working correctly!" if flt(getattr(test_po, 'custom_withholding_tax_amount', 0)) == 300 else "❌ Thai WHT calculation issue detected"
        }

        return results

    except Exception as e:
        return {
            "test_status": "error",
            "error_message": str(e),
            "message": f"❌ Test failed: {str(e)}"
        }